name: Publish to PYPI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twine
    - name: Build manylinux Python wheels
      uses: RalfG/python-wheels-manylinux-build@v0.3.3-manylinux2010_x86_64
      with:
        python-versions: 'cp36-cp36m cp37-cp37m'
        build-requirements: 'numpy'
        system-packages: 'build-essential python3-dev python3-setuptools make cmake ffmpeg libavcodec-dev libavfilter-dev libavformat-dev libavutil-dev'
        pre-build-command: 'ffmpeg -version && mkdir build && cd build && cmake .. -DUSE_CUDA=0 && cd build && make -j$(nproc)'
        package-path: 'python'
        pip-wheel-args: '-w ./dist'
    - name: Publish wheels to PyPI
      run: |
        ls dist/*
